title: Meu Blog
author: Voxy
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Criando esse blog om ajudar do GitHub Learning Lab!
  Obrigado por me ajudar. :D

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
